### PR TITLE
Allow to set seed end to 0x7FFFFFFF

### PR DESCRIPTION
**Pull request by binarymaster**
Not sure whether this is correct solution, since pixiewps exits too fast for me (with `--start 01/1970 --end 02/2038`).

### CODE REVIEW

**Comment by wiire-a** [comment]
It's a signed integer, the maximum is **0x7FFFFFFF**, that is why I used
```C
(time_t)-1
```
as "invalid value" (which is **0xFFFFFFFF**).

See: https://en.wikipedia.org/wiki/Year_2038_problem

I don't know it really makes sense to be able to reach that point anyway (by that logic it should be also possible to test with negative values).

**Comment by binarymaster** [comment]
You're right, updated the commit.

But it's theoretically possible for APs to use negative value for seed initializing?

**Comment by wiire-a** [comment]
> You're right, updated the commit.

The code looks okay at a quick glance but before deciding if to merge or not I need to check it thoroughly, since we are close to a new release.

> But is it theoretically possible for APs to use negative value for seed initializing?

I doubt it. Maybe if *gettimeofday()* fails? I don't even know if it can fail. In any case the new PRNG doesn't support negative seeding at the moment, so that would need tweaking too.

**Comment by binarymaster** [comment]
Ok, let it be just one simple change for now. :smile: 

I've pushed previous commits to my [unlimit-seed](https://github.com/binarymaster/pixiewps/commits/unlimit-seed) branch.

**Pull request merged**
