### PR TITLE
use tomsfastmath instead of tommath hack from wpa_supplicant

### PR DESCRIPTION
**Pull request by rofl0r**

### CODE REVIEW

**Comment by rofl0r** [comment]
new code:

 [*] Time taken: 0 s 10 ms

old code:

 [*] Time taken: 0 s 24 ms


other benefits:
- removed BSD-licensed files by wpa_supplicant author

only non-public-domain 3rd party sources left are mbedtls sha256 code and aes code from wpa_supplicant (both could be replaced with PD libtomcrypt)

- compilation can use additional cores to speed up build of the split up .c files

- tomsfastmath doesn't use malloc, so it cannot fail


disadvantages:
- currently, with this change compilation using a single core is slower than before
this might be mitigated by compiling the TU's from tfm with -O0

**Comment by wiire-a** [comment]
Did you check the binary size before and after? It's > 2.5x larger. Using `-flto` reduces it a bit but it's still "huge". There are probably some defines that make the code faster but produce a much bigger binary.

On another note, with these changes the Android Makefile needs to be changed as well. Yes, I forgot to update it too with my last commits. Also, you forgot to `git pull` before making your changes.

> only non-public-domain 3rd party sources left are mbedtls sha256 code and aes code from wpa_supplicant (both could be replaced with PD libtomcrypt)

Replacing the current AES code with libtomcrypt is a welcome addition.

I want to switch from mbedtls SHA256 routines to something else, faster (still preserving portability). Speed is not really a concern right now since we don't do many iterations, but that may change soon in the future. So, IMO, it's better to do some testing and comparisons before committing blindly to libtomcrypt, since changing library means changing interface (function prototypes) and may need refactoring rather that simple ifdefs wrappers (generally speaking, not in that specific case - I honestly didn't check).

**Comment by rofl0r** [comment]
yeah, the binary is 2.5x larger and 2.5x faster - that's the tradeoff here :)
otoh, with 240kb, its not really big either.

**Comment by wiire-a** [comment]
Commenting these out seems to bring the binary back to the same size as the original without major speed downsides:

```C
/* #define TFM_SMALL_SET */

/* do we want huge code
   Enable these if you are doing 20, 24, 28, 32, 48, 64 digit multiplications (useful for RSA)
   Less important on 64-bit machines as 32 digits == 2048 bits
 */
#if 0
#define TFM_MUL3
#define TFM_MUL4
#define TFM_MUL6
#define TFM_MUL7
#define TFM_MUL8
#define TFM_MUL9
#define TFM_MUL12
#define TFM_MUL17

#define TFM_MUL20
#define TFM_MUL24
#define TFM_MUL28
#define TFM_MUL32
#define TFM_MUL48
#define TFM_MUL64
#endif

#if 0
#define TFM_SQR3
#define TFM_SQR4
#define TFM_SQR6
#define TFM_SQR7
#define TFM_SQR8
#define TFM_SQR9
#define TFM_SQR12
#define TFM_SQR17

#define TFM_SQR20
#define TFM_SQR24
#define TFM_SQR28
#define TFM_SQR32
#define TFM_SQR48
#define TFM_SQR64
#endif
```

7 ms vs 9 ms

But I didn't look further in the sources.

Also if we merge this, the `<stdarg.h>` include in pixiewps can go.

**Comment by wiire-a** [comment]
Thank you :)

**Pull request merged**
